import uuid
from io import BytesIO

from sqlalchemy.orm import Session

from app.repositories.ai import ConversationRepository, SessionRepository
from app.schemas.auth import CurrentUser
from app.schemas.chatbot import ChatMemoryItem, ChatMemoryResponse, ChatRequest, ChatResponse, PdfExportRequest
from app.services.ai_chatbot import AiChatbotEngine


class ChatbotService:
    def __init__(self, db: Session):
        self.db = db

    def ask(self, payload: ChatRequest, user: CurrentUser) -> ChatResponse:
        session_id = uuid.UUID(payload.session_id) if payload.session_id else None
        if not session_id:
            session = SessionRepository(self.db).create(
                user_id=user.user_id,
                role_code=user.role,
                unit_code=user.unit_code,
                district_code=user.district_code,
            )
            session_id = session.session_id

        repo = ConversationRepository(self.db)
        sequence = repo.next_sequence(session_id)
        result = AiChatbotEngine(self.db).answer(
            question=payload.message,
            requested_language=payload.language,
            execute_sql=payload.execute_sql,
        )
        row = repo.create(
            session_id=session_id,
            user_id=user.user_id,
            message_sequence=sequence,
            user_prompt=payload.message,
            assistant_response=result.answer,
            intent_name=result.intent,
            tool_name="langchain_llama3_sql_rag_agent",
            generated_sql=result.generated_sql,
            official_tables_used=["CaseMaster", "Accused"],
            evidence_refs=result.evidence_refs,
            confidence_score=result.confidence_score,
            explanation=result.explanation,
        )
        return ChatResponse(
            session_id=str(session_id),
            answer=result.answer,
            intent=row.intent_name or "unknown",
            language=payload.language,
            generated_sql=result.generated_sql,
            sql_rows=result.rows,
            evidence_refs=result.evidence_refs,
            explanation=result.explanation,
            confidence_score=result.confidence_score,
            voice_text=result.answer if payload.enable_voice_output else None,
        )

    def memory(self, session_id: str) -> ChatMemoryResponse:
        rows = ConversationRepository(self.db).list_by_session(uuid.UUID(session_id))
        return ChatMemoryResponse(
            session_id=session_id,
            items=[
                ChatMemoryItem(
                    message_sequence=row.message_sequence,
                    user_prompt=row.user_prompt,
                    assistant_response=row.assistant_response,
                    intent_name=row.intent_name,
                    generated_sql=row.generated_sql,
                )
                for row in rows
            ],
        )

    def export_pdf(self, payload: PdfExportRequest) -> bytes:
        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.pdfgen import canvas
        except ModuleNotFoundError:
            return self._plain_pdf_fallback(payload)

        buffer = BytesIO()
        pdf = canvas.Canvas(buffer, pagesize=A4)
        width, height = A4
        y = height - 48
        pdf.setFont("Helvetica-Bold", 14)
        pdf.drawString(48, y, payload.title)
        y -= 28
        pdf.setFont("Helvetica", 9)
        pdf.drawString(48, y, "Generated by CrimeX AI. Verify all outputs against official FIR records.")
        y -= 28

        for item in payload.messages[:40]:
            text = f"{item.get('role', 'message')}: {item.get('content', '')}"
            for line in self._wrap(text, 92):
                if y < 54:
                    pdf.showPage()
                    y = height - 48
                    pdf.setFont("Helvetica", 9)
                pdf.drawString(48, y, line)
                y -= 14
            y -= 8

        pdf.save()
        buffer.seek(0)
        return buffer.read()

    def _wrap(self, value: str, width: int) -> list[str]:
        return [value[index : index + width] for index in range(0, len(value), width)] or [""]

    def _plain_pdf_fallback(self, payload: PdfExportRequest) -> bytes:
        body = [payload.title, "CrimeX AI Conversation Export"]
        body.extend(f"{item.get('role', 'message')}: {item.get('content', '')}" for item in payload.messages)
        return ("\n\n".join(body)).encode("utf-8")
